apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - paul.wtf
